### ISSUE TITLE
mktexfmt [WARNING]: resetting $HOME value (was /github/home) to root's actual home (/root).

### ISSUE THREAD

**Issue by ckirsch** [listx/texlive-docker#3]
Hi @listx 

I noticed that my homepage build based on your texlive docker image stopped working, see:

https://github.com/ckirsch/ckirsch.github.com/runs/741388181?check_suite_focus=true

Please let me know if you have time to look into this. I am glad to provide feedback.

**Comment by listx** [comment]
I don't have the bandwidth right now to do a deep-dive debug of this on my own. It would be great if you could provide details about (1) how this image was used before and (2) what has changed.

I poked around in the link you posted and did some Google searching to find https://tex.stackexchange.com/questions/64894/error-i-cant-find-the-format-file-pdflatex-fmt which might be relevant.

**Comment by ckirsch** [comment]
I did not change anything. The error occurred during a scheduled weekly run without any changes to my code since the last successful run a week before. However, you seem to have changed something on your side during that time. It may therefore be easy for you to check your most recent changes and find the issue. But never mind if you don't have time. I will probably look into creating my own vanilla texlive docker image which is all I need.

**Comment by listx** [comment]
I've only changed 3 things (see commit history for master branch) in this year. None of them bear any relation to the error you are seeing (the title of this issue is misleading because that is not the actual error message I see in the link you posted).

If I had to guess, it's the way the Arch package managers changed how TexLive is packaged.
